server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: materiales
            uri: http://localhost:8081
            predicates:
              - Path=/materiales/**
          - id: productos
            uri: http://localhost:8082
            predicates:
              - Path=/productos/**
          - id: ventas
            uri: http://localhost:8083
            predicates:
              - Path=/ventas/**
          - id: categorias
            uri: http://localhost:8084
            predicates:
              - Path=/categorias/**
          - id: pedidos
            uri: http://localhost:8085
            predicates:
              - Path=/pedidos/**
          - id: pedido-materiales
            uri: http://localhost:8085
            predicates:
              - Path=/pedido-materiales/**