server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: materiales
            uri: http://localhost:8081
            predicates:
              - Path=/materiales/**
          - id: productos
            uri: http://localhost:8082
            predicates:
              - Path=/productos/**
          - id: ventas
            uri: http://localhost:8083
            predicates:
              - Path=/ventas/**
          - id: categorias
            uri: http://localhost:8084
            predicates:
              - Path=/categorias/**
          - id: pedidos
            uri: http://localhost:8085
            predicates:
              - Path=/pedidos/**
          - id: pedido-materiales
            uri: http://localhost:8085
            predicates:
              - Path=/pedido-materiales/**
          - id: proveedores
            uri: http://localhost:8086
            predicates:
              - Path=/proveedores/**
          - id: proveedor-materiales
            uri: http://localhost:8086
            predicates:
              - Path=/proveedor-materiales/**
          - id: reportes
            uri: http://localhost:8087
            predicates:
              - Path=/reportes/**
          - id: galeria
            uri: http://localhost:8088
            predicates:
              - Path=/galeria/**
          - id: gastos
            uri: http://localhost:8089
            predicates:
              - Path=/gastos/**
          - id: categorias-gasto
            uri: http://localhost:8089
            predicates:
              - Path=/categorias-gasto/**