spring.application.name=service_calendario

server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/db_calendario?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

microservicio.productos.url=http://localhost:8086
microservicio.pedidos.url=http://localhost:8087